development: &development
  adapter: postgresql
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: conflict_free_schema

test:
  <<: *development
  host: <%= ENV.fetch('POSTGRES_HOST', 'postgres') %>
